version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: dns-backend
    ports:
      - "5000:5000"
    networks:
      - dnsnet
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: dns-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - dnsnet
    restart: unless-stopped

networks:
  dnsnet:
    driver: bridge
